import PDFDocument from 'pdfkit';
import logger from '../logger.js';

/**
 * Generate a PDF itinerary document.
 */
export function generateItineraryPDF(itinerary) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: 'A4',
        margin: 50,
        bufferPages: true,
        info: {
          Title: `Trip to ${itinerary.destination}`,
          Author: 'TripPlanner AI',
        },
      });

      const chunks = [];
      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // Header
      doc.fontSize(28).font('Helvetica-Bold')
        .text(`Trip to ${itinerary.destination}`, { align: 'center' });
      doc.moveDown(0.5);
      doc.fontSize(12).font('Helvetica')
        .fillColor('#666')
        .text(`${itinerary.country} | ${itinerary.days?.length || '?'} Days`, { align: 'center' });
      doc.moveDown(0.3);
      doc.fontSize(10)
        .text(`Generated by TripPlanner AI`, { align: 'center' });

      // Local Tips
      if (itinerary.localTips?.length) {
        doc.moveDown(1);
        doc.fontSize(14).font('Helvetica-Bold').fillColor('#333')
          .text('Local Tips');
        doc.moveDown(0.3);
        for (const tip of itinerary.localTips) {
          doc.fontSize(10).font('Helvetica').fillColor('#555')
            .text(`• ${tip}`, { indent: 10 });
        }
      }

      // Emergency Numbers
      if (itinerary.emergencyNumbers) {
        doc.moveDown(0.8);
        doc.fontSize(14).font('Helvetica-Bold').fillColor('#333')
          .text('Emergency Numbers');
        doc.moveDown(0.3);
        for (const [key, val] of Object.entries(itinerary.emergencyNumbers)) {
          doc.fontSize(10).font('Helvetica').fillColor('#555')
            .text(`${key}: ${val}`, { indent: 10 });
        }
      }

      // Days
      if (itinerary.days?.length) {
        for (const day of itinerary.days) {
          doc.addPage();

          // Day header
          doc.fontSize(20).font('Helvetica-Bold').fillColor('#1a73e8')
            .text(`Day ${day.day}: ${day.theme || ''}`);
          if (day.area) {
            doc.fontSize(11).font('Helvetica').fillColor('#888')
              .text(`Area: ${day.area}`);
          }
          doc.moveDown(0.5);

          // Budget
          if (day.estimatedBudget) {
            doc.fontSize(10).font('Helvetica-Bold').fillColor('#333')
              .text(`Estimated Budget: ${day.estimatedBudget.amount} ${day.estimatedBudget.currency}`);
            doc.moveDown(0.5);
          }

          // Activities
          if (day.activities?.length) {
            for (const activity of day.activities) {
              const timeStr = activity.timeStart
                ? `${activity.timeStart} – ${activity.timeEnd || ''}`
                : activity.slot;

              // Travel info
              if (activity.travelFromPrevious?.minutes) {
                doc.fontSize(9).font('Helvetica').fillColor('#999')
                  .text(`↓ ${activity.travelFromPrevious.minutes} min by ${activity.travelFromPrevious.method}`, { indent: 20 });
                doc.moveDown(0.2);
              }

              doc.fontSize(12).font('Helvetica-Bold').fillColor('#333')
                .text(`${timeStr}  —  ${activity.name}`);

              doc.fontSize(10).font('Helvetica').fillColor('#555')
                .text(activity.description || '', { indent: 10 });

              if (activity.budgetEstimate) {
                doc.fontSize(9).fillColor('#888')
                  .text(`Budget: ${activity.budgetEstimate}`, { indent: 10 });
              }
              if (activity.tips) {
                doc.fontSize(9).fillColor('#1a73e8')
                  .text(`Tip: ${activity.tips}`, { indent: 10 });
              }
              doc.moveDown(0.5);
            }
          }
        }
      }

      // Footer on all pages
      const pages = doc.bufferedPageRange();
      for (let i = 0; i < pages.count; i++) {
        doc.switchToPage(i);
        doc.fontSize(8).font('Helvetica').fillColor('#ccc')
          .text(
            `TripPlanner AI — Page ${i + 1} of ${pages.count}`,
            50, doc.page.height - 40,
            { align: 'center', width: doc.page.width - 100 }
          );
      }

      doc.end();
    } catch (err) {
      logger.error('PDF generation failed:', err);
      reject(err);
    }
  });
}

export default { generateItineraryPDF };
